### ISSUE TITLE
Changing marker size

### ISSUE THREAD

**Issue by Kanonck** [usrl-uofsc/stag_ros#1]
Hello,
I am currently trying out this ROS package for a university project and have already configured the correct marker id and camera that I use but could not figure out yet how to change the marker size. Could you help me out here? Also the cfg/single.json file doesn't exist.
Thanks a lot!

**Comment by MikeK4y** [comment]
We changed the marker config files from json to yaml so that's why the cfg/single.json doesn't exist anymore. The config file for a single marker was named **bundle_config_single.yaml** but I just changed it to **single_config.yaml**.

To set your marker size you need to change the positions of the corners in the marker config file. The example file **single_config.yaml** is for a marker that is 16.1cm wide with the reference placed on its center

**Comment by Abhinavgandhi09** [comment]
Is there a recommended method for scaling the marker images for printing purposes? I want to print markers of 20mm x 20mm. Would the library detect them accurately if they are as small?

Thanks!

**Comment by Kanonck** [comment]
> We changed the marker config files from json to yaml so that's why the cfg/single.json doesn't exist anymore. The config file for a single marker was named **bundle_config_single.yaml** but I just changed it to **single_config.yaml**.
> 
> To set your marker size you need to change the positions of the corners in the marker config file. The example file **single_config.yaml** is for a marker that is 16.1cm wide with the reference placed on its center

Thanks a lot!

**Comment by Abhinavgandhi09** [comment]
Yes I read that. My question is about the pngs themselves in the drive folder. Is there a recommended way to scale those for print? And have you tested markers using small sizes like 20 x 20 mm? Do they work well?

**Comment by Brenn10** [comment]
In our paper, we used the tags at different distances which proportionally scaled the size down. I would definitely recommend trying it, but 2cm is very small and would be hard to view from a long distance or with a low resolution camera since there would be very few pixels in the region of the tag.
