### ISSUE TITLE
Flaky transform between camera and STag 

### ISSUE THREAD

**Issue by dorkamotorka** [usrl-uofsc/stag_ros#3]
While detection of the markers is well, it's pose estimation is really wrong. I would say there are some singularities in the code.

I am appending the error messages I get due to stag_ros.
![image](https://user-images.githubusercontent.com/48418580/100865717-03e5d780-3498-11eb-9c46-f05356536bde.png)
![image](https://user-images.githubusercontent.com/48418580/100865823-224bd300-3498-11eb-807c-ce9d2131191c.png)

Also when I visualize it in Rviz the transform of the stag according to the camera is like in infinity and jumping around.

**Comment by dorkamotorka** [comment]
I ran the stagNode.launch on kinetic-devel branch. I ran it on Raspberry Pi 4 with Kinetic.

**Comment by MikeK4y** [comment]
Are you running it with the sample files or on your own setup? Try running it with the sample files and if it still crashes post the output here.

If you are running it with your own setup make sure that the marker config file and the camera info are both correct

**Comment by dorkamotorka** [comment]
![image](https://user-images.githubusercontent.com/48418580/100983709-fa1cac80-3549-11eb-880c-405683cff660.png)
![image](https://user-images.githubusercontent.com/48418580/100983773-1587b780-354a-11eb-9929-3f2a09d91ca5.png)

I ran the stagNode.launch which includes these two configuration files. The stag was from Library HD 13.

**Comment by dorkamotorka** [comment]
Should I be testing marker with ID 7?

**Comment by MikeK4y** [comment]
The id in the marker config file should match the one that you are trying to detect. Just set the libraryHD parameter to the one you want to use and set the id of the tags to the marker id you want to detect

**Comment by Brenn10** [comment]
Would it be possible for you to post a sample rosbag so that we could work on the issue?

**Comment by dorkamotorka** [comment]
Changing the marker id  in the config file to the one I am detecting solves the problem. I will re-open a new issue because I would like to detect the whole set of markers not just a specific ID.

**Comment by Brenn10** [comment]
I'm reopening this issue as our software shouldn't give  us any bad quaternions in any case. I presume this will be an issue across all of our branches and needs to be fixed.

**Comment by dorkamotorka** [comment]
Changing the ID to appropriate solves the quaternion problem. So if the ID in the .cfg file is not right Rviz crashes and user gets a quaternion error - maybe you should at least make a graceful shutdown.

**Comment by tp4348** [comment]
Is there any clue or any configuration files I can refer to, so I will be able to detect multiple markers of different IDs?

**Comment by Brenn10** [comment]
Library HD validity checking has been added in https://github.com/usrl-uofsc/stag_ros/commit/0d8c0a0c90eb071e79cfae6c777bf49018e00528

The tag id issue appears to be fixed in https://github.com/usrl-uofsc/stag_ros/commit/3f372626543f3ab26db109b3bd479adb38eebf44

Errors will no longer be thrown for inputting the wrong tag id, but no pose data will be published either. An invalid_argument exception will be thrown and caught to gracefully exit if an invalid library HD is input, but a valid but wrong libraryHD will result in no pose information being published.

I am closing on these. Please let us know if you continue to receive non-graceful shutdowns from inputting an improper tag id.
:smile:
